services:
  raytracer-perf:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: raytracer-perf

    working_dir: /workspace

    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE

    security_opt:
      - seccomp=unconfined

    command: tail -f /dev/null